### ISSUE TITLE
How to get directory items

### ISSUE THREAD

**Issue by vasyl-shumskyi** [daaku/nodejs-walker#11]
Thanks for an awesome module. 

I would like to get directory items (just the names). I can do extra check with `fs.readdir()` like the following:

```javascript
.on('dir', function(dir, stat) {
    fs.readdir(dir, callback)
})

```

Just curious if there is one-shot solution? 

Thanks!

**Comment by daaku** [comment]
By default it is recursive (which you can control with the `filterDir` callback). Maybe that's what you need? It's difficult for me to understand what you're trying to achieve with the snippet you've provided.

**Comment by vasyl-shumskyi** [comment]
Thanks for your response. I would like to list items _non_ recursively in _every_ folder.

**Comment by daaku** [comment]
That seems like a more specific solution than what this module was meant for.
