### ISSUE TITLE
Enter symlink directories

### ISSUE THREAD

**Issue by bpatram** [daaku/nodejs-walker#13]
Hello! It seems walker will not enter directories which are symlinked (or consider symlinked directories a 'normal' directory). 

In my case, I use the extension for VSCode https://github.com/alefragnani/vscode-project-manager which uses this library. I have a directory which is a symlink but sadly, no projects in that folder will get picked up due to the symlink. 
You can see the related issue here: https://github.com/alefragnani/vscode-project-manager/issues/274  

Is there a reason to treat symlinked directories different than a normal directory?

**Comment by daaku** [comment]
> Is there a reason to treat symlinked directories different than a normal directory?

Well, they are *different*, so they're not treated the same. It's up to the user of this library to handle it as they see fit. Code below can serve as a guide; though symlinks have complications like cycles, invalid symlinks, not to mention they can be pointing to not only directories and files, but also devices, sockets etc.

```js
const Walker = require('walker');
const fs = require('fs');

Walker('/etc')
  .on('entry', function(entry, stat) {
    console.log('Got entry: ' + entry)
  })
  .on('symlink', function(symlink, stat) {
    this.go(fs.realpathSync(symlink));
  });
```
