### ISSUE TITLE
Check recursively if dir contains files and exit earlier

### ISSUE THREAD

**Issue by vasyl-shumskyi** [daaku/nodejs-walker#14]
I try to check recursively if dir contain files

The issue is that I can't exit earlier once first file found without scanning all directory tree. 

Check out the code below:

```javascript
function dir_contains_files(dir) {

    let files = 0
    const walker = require('walker')

    return walker(dir)

    .on('file', (file, stats) => {
        files++
        console.log(files)
        return files
    })

    .on('error', (err, entry) => {
        console.warn(err, entry)
    })

    .on('end', function() {
       console.log(files)
    })
}
```

  [1]: https://www.npmjs.com/package/walker

**Comment by daaku** [comment]
While that would be a nice feature to have, this project is "done" feature wise and I'll only be fixing bugs if any arise.
